apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscalegroup
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: c-company-rest-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 85
