apiVersion: v1
kind: Service
metadata:
  name: c-company-rest-node
  labels:
    app: c-company-rest-node
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: c-company-rest-deployment
