apiVersion: v1
kind: Service
metadata:
  name: c-company-rest
  labels:
    app: c-company-rest
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: c-company-rest
